"""
DORIAN MATHEMATICS DOMAIN
=========================

Comprehensive mathematical knowledge for Dorian Core.

Includes:
1. Extended category hierarchy (algebra, analysis, geometry, logic, etc.)
2. Mathematical relations (proves, implies, equivalent_to, etc.)
3. Axioms and foundational facts
4. Theorems and their relationships
5. Mathematical properties (commutative, associative, etc.)

Structure:
- Categories: Types of mathematical objects
- Relations: How mathematical objects relate
- Facts: Axioms, definitions, theorems

Author: Joseph + Claude
Date: 2026-01-25
"""

from dataclasses import dataclass
from typing import Dict, List, Set, Tuple

# =============================================================================
# MATHEMATICAL CATEGORIES (to extend ontology)
# =============================================================================

MATH_CATEGORIES = [
    # =========================================================================
    # NUMBERS (extending existing)
    # =========================================================================
    (
        "prime_number",
        "natural_number",
        "A natural number greater than 1 with no divisors other than 1 and itself",
    ),
    (
        "composite_number",
        "natural_number",
        "A natural number greater than 1 that is not prime",
    ),
    ("even_number", "integer", "An integer divisible by 2"),
    ("odd_number", "integer", "An integer not divisible by 2"),
    (
        "irrational_number",
        "real_number",
        "A real number that cannot be expressed as a ratio of integers",
    ),
    (
        "transcendental_number",
        "irrational_number",
        "A number that is not the root of any polynomial with integer coefficients",
    ),
    (
        "algebraic_number",
        "complex_number",
        "A number that is a root of a polynomial with integer coefficients",
    ),
    ("imaginary_number", "complex_number", "A complex number with zero real part"),
    ("quaternion", "number", "A number system extending complex numbers"),
    ("ordinal_number", "number", "A number describing position in a sequence"),
    ("cardinal_number", "number", "A number describing the size of a set"),
    # =========================================================================
    # SETS AND COLLECTIONS
    # =========================================================================
    ("empty_set", "set", "The set containing no elements"),
    ("finite_set", "set", "A set with a finite number of elements"),
    ("infinite_set", "set", "A set with infinitely many elements"),
    (
        "countable_set",
        "infinite_set",
        "An infinite set that can be put in one-to-one correspondence with natural numbers",
    ),
    (
        "uncountable_set",
        "infinite_set",
        "An infinite set that cannot be put in one-to-one correspondence with natural numbers",
    ),
    ("ordered_set", "set", "A set with a total ordering on its elements"),
    ("power_set", "set", "The set of all subsets of a given set"),
    ("cartesian_product", "set", "The set of all ordered pairs from two sets"),
    # =========================================================================
    # ALGEBRAIC STRUCTURES
    # =========================================================================
    (
        "monoid",
        "mathematical_structure",
        "A set with an associative binary operation and identity element",
    ),
    (
        "semigroup",
        "mathematical_structure",
        "A set with an associative binary operation",
    ),
    ("abelian_group", "group", "A group where the operation is commutative"),
    ("cyclic_group", "group", "A group generated by a single element"),
    ("symmetric_group", "group", "The group of all permutations of a set"),
    ("commutative_ring", "ring", "A ring where multiplication is commutative"),
    ("integral_domain", "commutative_ring", "A commutative ring with no zero divisors"),
    (
        "euclidean_domain",
        "integral_domain",
        "An integral domain with a Euclidean function",
    ),
    (
        "principal_ideal_domain",
        "integral_domain",
        "An integral domain where every ideal is principal",
    ),
    (
        "unique_factorization_domain",
        "integral_domain",
        "An integral domain where every element has unique factorization",
    ),
    ("ordered_field", "field", "A field with a compatible total order"),
    (
        "complete_field",
        "ordered_field",
        "An ordered field where every Cauchy sequence converges",
    ),
    ("algebra", "mathematical_structure", "A vector space with a bilinear product"),
    (
        "lie_algebra",
        "algebra",
        "An algebra with antisymmetric bracket satisfying the Jacobi identity",
    ),
    (
        "module",
        "mathematical_structure",
        "A generalization of vector spaces over a ring",
    ),
    (
        "ideal",
        "mathematical_structure",
        "A special subset of a ring closed under ring multiplication",
    ),
    # =========================================================================
    # LINEAR ALGEBRA
    # =========================================================================
    ("vector", "mathematical_object", "An element of a vector space"),
    ("matrix", "mathematical_object", "A rectangular array of numbers"),
    ("square_matrix", "matrix", "A matrix with equal number of rows and columns"),
    (
        "diagonal_matrix",
        "square_matrix",
        "A square matrix with non-zero entries only on the diagonal",
    ),
    (
        "identity_matrix",
        "diagonal_matrix",
        "A diagonal matrix with all diagonal entries equal to 1",
    ),
    (
        "invertible_matrix",
        "square_matrix",
        "A square matrix with a multiplicative inverse",
    ),
    (
        "orthogonal_matrix",
        "invertible_matrix",
        "A matrix whose inverse equals its transpose",
    ),
    ("symmetric_matrix", "square_matrix", "A matrix equal to its transpose"),
    (
        "hermitian_matrix",
        "square_matrix",
        "A complex matrix equal to its conjugate transpose",
    ),
    ("eigenvalue", "number", "A scalar associated with a linear transformation"),
    (
        "eigenvector",
        "vector",
        "A vector whose direction is unchanged by a linear transformation",
    ),
    ("determinant", "number", "A scalar value computed from a square matrix"),
    ("trace", "number", "The sum of diagonal entries of a square matrix"),
    (
        "linear_transformation",
        "function",
        "A function preserving vector addition and scalar multiplication",
    ),
    (
        "linear_map",
        "linear_transformation",
        "A linear transformation between vector spaces",
    ),
    ("inner_product", "binary_operation", "A generalization of the dot product"),
    ("norm", "function", "A function measuring the size of vectors"),
    ("inner_product_space", "vector_space", "A vector space with an inner product"),
    ("hilbert_space", "inner_product_space", "A complete inner product space"),
    ("banach_space", "vector_space", "A complete normed vector space"),
    # =========================================================================
    # ANALYSIS
    # =========================================================================
    ("sequence", "function", "A function from natural numbers to a set"),
    ("series", "mathematical_object", "A sum of a sequence"),
    ("convergent_sequence", "sequence", "A sequence with a limit"),
    (
        "cauchy_sequence",
        "sequence",
        "A sequence where terms eventually get arbitrarily close",
    ),
    ("limit", "mathematical_object", "The value a sequence or function approaches"),
    ("continuous_function", "function", "A function with no breaks or jumps"),
    (
        "differentiable_function",
        "continuous_function",
        "A function with a derivative at every point",
    ),
    (
        "analytic_function",
        "differentiable_function",
        "A function locally given by a convergent power series",
    ),
    ("derivative", "function", "The rate of change of a function"),
    (
        "integral",
        "mathematical_object",
        "The accumulation of a function over an interval",
    ),
    ("definite_integral", "integral", "An integral with specified bounds"),
    ("indefinite_integral", "integral", "An antiderivative of a function"),
    ("partial_derivative", "derivative", "A derivative with respect to one variable"),
    ("gradient", "vector", "The vector of partial derivatives"),
    ("divergence", "function", "A scalar measure of a vector field's expansion"),
    ("curl", "vector", "A vector measure of rotation in a vector field"),
    ("laplacian", "function", "The divergence of the gradient"),
    ("taylor_series", "series", "A power series representation of a function"),
    (
        "fourier_series",
        "series",
        "A representation of a function as a sum of sinusoids",
    ),
    ("power_series", "series", "A series of powers of a variable"),
    ("metric", "function", "A function defining distance between points"),
    ("metric_space", "mathematical_structure", "A set with a metric"),
    (
        "complete_metric_space",
        "metric_space",
        "A metric space where every Cauchy sequence converges",
    ),
    # =========================================================================
    # TOPOLOGY
    # =========================================================================
    ("open_set", "set", "A set containing a neighborhood of each of its points"),
    ("closed_set", "set", "A set whose complement is open"),
    ("compact_set", "set", "A set where every open cover has a finite subcover"),
    (
        "connected_set",
        "set",
        "A set that cannot be partitioned into two non-empty open sets",
    ),
    ("homeomorphism", "function", "A continuous bijection with continuous inverse"),
    ("manifold", "topological_space", "A space locally resembling Euclidean space"),
    ("smooth_manifold", "manifold", "A manifold with smooth transition functions"),
    ("riemannian_manifold", "smooth_manifold", "A manifold with a Riemannian metric"),
    # =========================================================================
    # GEOMETRY
    # =========================================================================
    ("point", "mathematical_object", "A location with no size"),
    ("line", "mathematical_object", "A one-dimensional geometric object"),
    ("plane", "mathematical_object", "A two-dimensional flat surface"),
    (
        "angle",
        "mathematical_object",
        "The figure formed by two rays with a common endpoint",
    ),
    ("triangle", "mathematical_object", "A polygon with three sides"),
    ("circle", "mathematical_object", "The set of points equidistant from a center"),
    (
        "sphere",
        "mathematical_object",
        "The set of points equidistant from a center in 3D",
    ),
    ("polygon", "mathematical_object", "A plane figure bounded by straight lines"),
    ("polyhedron", "mathematical_object", "A solid bounded by plane faces"),
    ("euclidean_space", "vector_space", "A vector space with Euclidean distance"),
    ("affine_space", "mathematical_structure", "A space with no distinguished origin"),
    (
        "projective_space",
        "mathematical_structure",
        "A space of lines through the origin",
    ),
    (
        "hyperbolic_space",
        "mathematical_structure",
        "A space with constant negative curvature",
    ),
    # =========================================================================
    # LOGIC AND FOUNDATIONS
    # =========================================================================
    ("axiom", "proposition", "A statement assumed to be true"),
    ("theorem", "proposition", "A statement proven from axioms and other theorems"),
    ("lemma", "theorem", "A minor theorem used to prove a larger theorem"),
    ("corollary", "theorem", "A theorem that follows easily from another"),
    ("conjecture", "proposition", "An unproven statement believed to be true"),
    ("definition", "proposition", "A statement giving the meaning of a term"),
    ("proof", "mathematical_object", "A logical argument establishing truth"),
    (
        "direct_proof",
        "proof",
        "A proof proceeding directly from premises to conclusion",
    ),
    (
        "proof_by_contradiction",
        "proof",
        "A proof assuming the negation and deriving a contradiction",
    ),
    ("proof_by_induction", "proof", "A proof using mathematical induction"),
    ("constructive_proof", "proof", "A proof that explicitly constructs an example"),
    ("predicate", "proposition", "A statement with variables"),
    ("quantifier", "mathematical_object", "An operator specifying quantity"),
    ("universal_quantifier", "quantifier", "The 'for all' quantifier"),
    ("existential_quantifier", "quantifier", "The 'there exists' quantifier"),
    # =========================================================================
    # OPERATIONS AND PROPERTIES
    # =========================================================================
    ("addition", "binary_operation", "The operation of combining quantities"),
    ("subtraction", "binary_operation", "The inverse of addition"),
    ("multiplication", "binary_operation", "Repeated addition or scaling"),
    ("division", "binary_operation", "The inverse of multiplication"),
    ("exponentiation", "binary_operation", "Repeated multiplication"),
    ("logarithm", "unary_operation", "The inverse of exponentiation"),
    ("composition", "binary_operation", "Applying one function after another"),
    ("convolution", "binary_operation", "An integral measuring overlap of functions"),
    # =========================================================================
    # PROPERTIES (as categories)
    # =========================================================================
    ("mathematical_property", "property", "A property of mathematical objects"),
    (
        "commutative_property",
        "mathematical_property",
        "The property that order doesn't matter",
    ),
    (
        "associative_property",
        "mathematical_property",
        "The property that grouping doesn't matter",
    ),
    (
        "distributive_property",
        "mathematical_property",
        "The property linking two operations",
    ),
    (
        "identity_property",
        "mathematical_property",
        "The property of having an identity element",
    ),
    ("inverse_property", "mathematical_property", "The property of having inverses"),
    (
        "closure_property",
        "mathematical_property",
        "The property that operations stay within a set",
    ),
    ("transitive_property", "mathematical_property", "If a~b and b~c then a~c"),
    ("reflexive_property", "mathematical_property", "a~a for all a"),
    ("symmetric_property", "mathematical_property", "If a~b then b~a"),
    ("antisymmetric_property", "mathematical_property", "If a~b and b~a then a=b"),
]


# =============================================================================
# MATHEMATICAL RELATIONS
# =============================================================================

MATH_RELATIONS = [
    # Proof relations
    (
        "proves",
        "X proves Y means X is a proof establishing Y",
        {"asymmetric", "irreflexive"},
    ),
    ("proven_by", "X proven_by Y means X is established by proof Y", {"asymmetric"}),
    ("assumes", "X assumes Y means X takes Y as a premise", {"asymmetric"}),
    (
        "follows_from",
        "X follows_from Y means X is a logical consequence of Y",
        {"transitive", "asymmetric"},
    ),
    (
        "generalizes",
        "X generalizes Y means X is a more general form of Y",
        {"asymmetric"},
    ),
    ("specializes", "X specializes Y means X is a special case of Y", {"asymmetric"}),
    # Mathematical equivalences
    (
        "isomorphic_to",
        "X isomorphic_to Y means X and Y have the same structure",
        {"symmetric", "transitive", "reflexive"},
    ),
    (
        "homeomorphic_to",
        "X homeomorphic_to Y means X and Y are topologically equivalent",
        {"symmetric", "transitive", "reflexive"},
    ),
    (
        "congruent_to",
        "X congruent_to Y means X and Y have the same shape and size",
        {"symmetric", "transitive", "reflexive"},
    ),
    (
        "similar_to",
        "X similar_to Y means X and Y have the same shape",
        {"symmetric", "transitive", "reflexive"},
    ),
    (
        "equivalent_to",
        "X equivalent_to Y means X and Y are mathematically equivalent",
        {"symmetric", "transitive", "reflexive"},
    ),
    # Set relations
    (
        "subset_of",
        "X subset_of Y means every element of X is in Y",
        {"transitive", "reflexive"},
    ),
    (
        "proper_subset_of",
        "X proper_subset_of Y means X subset_of Y and X ≠ Y",
        {"transitive", "irreflexive"},
    ),
    ("superset_of", "X superset_of Y means Y subset_of X", {"transitive", "reflexive"}),
    ("element_of", "X element_of Y means X is a member of set Y", {"asymmetric"}),
    (
        "disjoint_from",
        "X disjoint_from Y means X and Y have no common elements",
        {"symmetric"},
    ),
    # Order relations
    (
        "less_than",
        "X less_than Y means X < Y in some ordering",
        {"transitive", "irreflexive", "asymmetric"},
    ),
    (
        "greater_than",
        "X greater_than Y means X > Y in some ordering",
        {"transitive", "irreflexive", "asymmetric"},
    ),
    (
        "less_than_or_equal",
        "X less_than_or_equal Y means X ≤ Y",
        {"transitive", "reflexive"},
    ),
    (
        "greater_than_or_equal",
        "X greater_than_or_equal Y means X ≥ Y",
        {"transitive", "reflexive"},
    ),
    ("divides", "X divides Y means Y is a multiple of X", {"transitive", "reflexive"}),
    # Function relations
    ("maps_to", "X maps_to Y means the function sends X to Y", {"asymmetric"}),
    ("inverse_of", "X inverse_of Y means X and Y are inverse functions", {"symmetric"}),
    ("composition_of", "X composition_of Y,Z means X = Y ∘ Z", {"asymmetric"}),
    # Structural relations
    (
        "has_identity",
        "X has_identity Y means Y is the identity element of X",
        {"asymmetric", "functional"},
    ),
    ("has_inverse", "X has_inverse Y means Y is the inverse of X", {"asymmetric"}),
    ("satisfies", "X satisfies Y means X fulfills property/axiom Y", {"asymmetric"}),
    ("defined_by", "X defined_by Y means Y is the definition of X", {"asymmetric"}),
    (
        "computed_by",
        "X computed_by Y means Y is an algorithm/method to compute X",
        {"asymmetric"},
    ),
    # Approximation
    ("approximates", "X approximates Y means X is close to Y", {"asymmetric"}),
    (
        "converges_to",
        "X converges_to Y means X approaches Y as a limit",
        {"asymmetric"},
    ),
    (
        "bounded_by",
        "X bounded_by Y means Y is an upper or lower bound for X",
        {"asymmetric"},
    ),
]


# =============================================================================
# MATHEMATICAL AXIOMS AND FACTS
# =============================================================================

MATH_FACTS = [
    # =========================================================================
    # NUMBER SYSTEM FACTS
    # =========================================================================
    # Number set containments
    ("natural_number", "subset_of", "integer"),
    ("integer", "subset_of", "rational_number"),
    ("rational_number", "subset_of", "real_number"),
    ("real_number", "subset_of", "complex_number"),
    ("irrational_number", "subset_of", "real_number"),
    ("prime_number", "subset_of", "natural_number"),
    ("even_number", "subset_of", "integer"),
    ("odd_number", "subset_of", "integer"),
    # Specific numbers
    ("zero", "is_a", "integer"),
    ("zero", "is_a", "even_number"),
    ("one", "is_a", "natural_number"),
    ("one", "is_a", "odd_number"),
    ("two", "is_a", "prime_number"),
    ("two", "is_a", "even_number"),
    ("pi", "is_a", "transcendental_number"),
    ("pi", "is_a", "irrational_number"),
    ("e", "is_a", "transcendental_number"),
    ("e", "is_a", "irrational_number"),
    ("i", "is_a", "imaginary_number"),
    ("sqrt_2", "is_a", "irrational_number"),
    ("sqrt_2", "is_a", "algebraic_number"),
    # =========================================================================
    # OPERATION PROPERTIES
    # =========================================================================
    # Addition properties
    ("addition", "has_property", "commutative_property"),
    ("addition", "has_property", "associative_property"),
    ("addition", "has_identity", "zero"),
    ("addition", "has_property", "closure_property"),
    # Multiplication properties
    ("multiplication", "has_property", "commutative_property"),
    ("multiplication", "has_property", "associative_property"),
    ("multiplication", "has_identity", "one"),
    ("multiplication", "has_property", "closure_property"),
    ("multiplication", "has_property", "distributive_property"),
    # Other operations
    ("subtraction", "inverse_of", "addition"),
    ("division", "inverse_of", "multiplication"),
    ("logarithm", "inverse_of", "exponentiation"),
    ("exponentiation", "is_not", "commutative_property"),
    ("subtraction", "is_not", "commutative_property"),
    ("division", "is_not", "commutative_property"),
    ("composition", "has_property", "associative_property"),
    ("composition", "is_not", "commutative_property"),
    # =========================================================================
    # STRUCTURE FACTS
    # =========================================================================
    # Group theory
    ("integer", "is_a", "abelian_group"),
    ("real_number", "is_a", "abelian_group"),
    ("real_number", "is_a", "field"),
    ("complex_number", "is_a", "field"),
    ("rational_number", "is_a", "field"),
    ("integer", "is_a", "integral_domain"),
    ("integer", "is_a", "euclidean_domain"),
    # Linear algebra
    ("euclidean_space", "is_a", "hilbert_space"),
    ("hilbert_space", "is_a", "banach_space"),
    ("identity_matrix", "has_property", "invertible_matrix"),
    ("orthogonal_matrix", "has_property", "invertible_matrix"),
    # =========================================================================
    # FUNDAMENTAL THEOREMS
    # =========================================================================
    # Arithmetic
    ("fundamental_theorem_of_arithmetic", "is_a", "theorem"),
    (
        "fundamental_theorem_of_arithmetic",
        "states",
        "every_integer_has_unique_prime_factorization",
    ),
    # Algebra
    ("fundamental_theorem_of_algebra", "is_a", "theorem"),
    ("fundamental_theorem_of_algebra", "states", "every_polynomial_has_complex_root"),
    # Calculus
    ("fundamental_theorem_of_calculus", "is_a", "theorem"),
    ("fundamental_theorem_of_calculus", "relates", "derivative"),
    ("fundamental_theorem_of_calculus", "relates", "integral"),
    # Other key theorems
    ("pythagorean_theorem", "is_a", "theorem"),
    ("pythagorean_theorem", "relates", "triangle"),
    ("pythagorean_theorem", "states", "a_squared_plus_b_squared_equals_c_squared"),
    ("eulers_identity", "is_a", "theorem"),
    ("eulers_identity", "states", "e_to_i_pi_plus_one_equals_zero"),
    ("eulers_identity", "relates", "e"),
    ("eulers_identity", "relates", "pi"),
    ("eulers_identity", "relates", "i"),
    ("prime_number_theorem", "is_a", "theorem"),
    ("prime_number_theorem", "relates", "prime_number"),
    ("prime_number_theorem", "states", "primes_distributed_like_n_over_log_n"),
    ("central_limit_theorem", "is_a", "theorem"),
    ("central_limit_theorem", "relates", "normal_distribution"),
    ("incompleteness_theorem", "is_a", "theorem"),
    ("incompleteness_theorem", "proven_by", "godel"),
    (
        "incompleteness_theorem",
        "states",
        "consistent_systems_cannot_prove_own_consistency",
    ),
    ("fermats_last_theorem", "is_a", "theorem"),
    ("fermats_last_theorem", "proven_by", "wiles"),
    (
        "fermats_last_theorem",
        "states",
        "no_integer_solutions_for_x_n_plus_y_n_equals_z_n_for_n_greater_than_2",
    ),
    # =========================================================================
    # AXIOM SYSTEMS
    # =========================================================================
    # Peano axioms
    ("peano_axioms", "is_a", "axiom"),
    ("peano_axioms", "defines", "natural_number"),
    ("peano_axiom_1", "states", "zero_is_natural_number"),
    ("peano_axiom_2", "states", "successor_of_natural_is_natural"),
    ("peano_axiom_3", "states", "zero_is_not_successor"),
    ("peano_axiom_4", "states", "equal_successors_means_equal_numbers"),
    ("peano_axiom_5", "states", "induction_principle"),
    # ZFC set theory
    ("zfc_axioms", "is_a", "axiom"),
    ("zfc_axioms", "defines", "set"),
    ("axiom_of_extensionality", "part_of", "zfc_axioms"),
    ("axiom_of_pairing", "part_of", "zfc_axioms"),
    ("axiom_of_union", "part_of", "zfc_axioms"),
    ("axiom_of_infinity", "part_of", "zfc_axioms"),
    ("axiom_of_power_set", "part_of", "zfc_axioms"),
    ("axiom_of_choice", "part_of", "zfc_axioms"),
    # Euclid's postulates
    ("euclids_postulates", "is_a", "axiom"),
    ("euclids_postulates", "defines", "euclidean_geometry"),
    ("parallel_postulate", "part_of", "euclids_postulates"),
    # =========================================================================
    # KEY MATHEMATICAL CONCEPTS
    # =========================================================================
    # Infinity
    ("infinity", "is_a", "mathematical_object"),
    ("countable_infinity", "is_a", "cardinal_number"),
    ("uncountable_infinity", "is_a", "cardinal_number"),
    ("aleph_null", "is_a", "countable_infinity"),
    ("continuum", "is_a", "uncountable_infinity"),
    ("real_number", "has_cardinality", "continuum"),
    ("natural_number", "has_cardinality", "aleph_null"),
    ("rational_number", "has_cardinality", "aleph_null"),
    # Important constants
    ("pi", "approximately_equals", "3.14159"),
    ("e", "approximately_equals", "2.71828"),
    ("golden_ratio", "approximately_equals", "1.61803"),
    ("golden_ratio", "is_a", "irrational_number"),
    ("golden_ratio", "is_a", "algebraic_number"),
    # =========================================================================
    # PROOF METHODS
    # =========================================================================
    ("proof_by_induction", "requires", "base_case"),
    ("proof_by_induction", "requires", "inductive_step"),
    ("proof_by_contradiction", "uses", "negation"),
    ("direct_proof", "uses", "logical_implication"),
    # =========================================================================
    # MATHEMATICAL RELATIONSHIPS
    # =========================================================================
    # Derivative rules
    ("derivative", "is_a", "linear_transformation"),
    ("derivative", "satisfies", "product_rule"),
    ("derivative", "satisfies", "chain_rule"),
    ("derivative", "satisfies", "quotient_rule"),
    # Integral rules
    ("integral", "inverse_of", "derivative"),
    ("definite_integral", "computes", "area_under_curve"),
    # Limits
    ("derivative", "defined_by", "limit"),
    ("integral", "defined_by", "limit"),
    ("continuity", "defined_by", "limit"),
    # =========================================================================
    # FAMOUS PROBLEMS AND CONJECTURES
    # =========================================================================
    ("riemann_hypothesis", "is_a", "conjecture"),
    ("riemann_hypothesis", "relates", "prime_number"),
    ("riemann_hypothesis", "unsolved", "true"),
    ("p_vs_np", "is_a", "conjecture"),
    ("p_vs_np", "relates", "complexity_class"),
    ("p_vs_np", "unsolved", "true"),
    ("collatz_conjecture", "is_a", "conjecture"),
    ("collatz_conjecture", "relates", "natural_number"),
    ("collatz_conjecture", "unsolved", "true"),
    ("twin_prime_conjecture", "is_a", "conjecture"),
    ("twin_prime_conjecture", "relates", "prime_number"),
    ("twin_prime_conjecture", "unsolved", "true"),
    ("goldbach_conjecture", "is_a", "conjecture"),
    ("goldbach_conjecture", "states", "every_even_greater_than_2_is_sum_of_two_primes"),
    ("goldbach_conjecture", "unsolved", "true"),
]


# =============================================================================
# MATHEMATICAL INFERENCE RULES
# =============================================================================


def get_math_inference_rules():
    """
    Return domain-specific inference rules for mathematics.

    These rules allow the system to derive new mathematical facts.
    """

    def subset_transitivity(facts):
        """If A subset_of B and B subset_of C, then A subset_of C."""
        inferred = []

        subset_facts = {}
        for f in facts:
            if f.predicate == "subset_of":
                if f.subject not in subset_facts:
                    subset_facts[f.subject] = []
                subset_facts[f.subject].append(f.object)

        # Transitive closure
        for a, bs in subset_facts.items():
            for b in bs:
                if b in subset_facts:
                    for c in subset_facts[b]:
                        if c not in bs:
                            inferred.append(
                                (
                                    a,
                                    "subset_of",
                                    c,
                                    f"Transitivity: {a} subset_of {b}, {b} subset_of {c}",
                                )
                            )

        return inferred

    def property_inheritance_math(facts):
        """If A is_a B and B has_property P, then A has_property P."""
        inferred = []

        # Build is_a graph
        is_a = {}
        for f in facts:
            if f.predicate == "is_a":
                if f.subject not in is_a:
                    is_a[f.subject] = []
                is_a[f.subject].append(f.object)

        # Find properties
        properties = {}
        for f in facts:
            if f.predicate == "has_property":
                if f.subject not in properties:
                    properties[f.subject] = []
                properties[f.subject].append(f.object)

        # Inherit properties
        for entity, parents in is_a.items():
            for parent in parents:
                if parent in properties:
                    for prop in properties[parent]:
                        inferred.append(
                            (
                                entity,
                                "has_property",
                                prop,
                                f"Property inheritance: {entity} is_a {parent}, {parent} has_property {prop}",
                            )
                        )

        return inferred

    def number_set_inference(facts):
        """Infer number type memberships from set relationships."""
        inferred = []

        # Build subset hierarchy
        subsets = {}
        for f in facts:
            if f.predicate == "subset_of":
                if f.subject not in subsets:
                    subsets[f.subject] = set()
                subsets[f.subject].add(f.object)

        # Build element_of facts
        elements = {}
        for f in facts:
            if f.predicate in ("is_a", "element_of"):
                if f.subject not in elements:
                    elements[f.subject] = set()
                elements[f.subject].add(f.object)

        # If x is_a A and A subset_of B, then x is_a B
        for entity, types in elements.items():
            for t in list(types):
                if t in subsets:
                    for supertype in subsets[t]:
                        if supertype not in types:
                            inferred.append(
                                (
                                    entity,
                                    "is_a",
                                    supertype,
                                    f"Set membership: {entity} is_a {t}, {t} subset_of {supertype}",
                                )
                            )

        return inferred

    return [
        ("mathematics", subset_transitivity),
        ("mathematics", property_inheritance_math),
        ("mathematics", number_set_inference),
    ]


# =============================================================================
# LOADER FUNCTION
# =============================================================================


def load_mathematics_into_core(core, agent_id: str = None) -> int:
    """
    Load all mathematics knowledge into a Dorian Core.

    Args:
        core: DorianCore instance
        agent_id: Agent ID to attribute facts to (creates one if None)

    Returns:
        Number of facts added
    """
    # Create math agent if needed
    if agent_id is None:
        math_agent = core.register_agent(
            "mathematics_loader", domain="mathematics", can_verify=True
        )
        agent_id = math_agent.agent_id

    count = 0

    # Add category facts (as is_a relations)
    print(f"  Loading {len(MATH_CATEGORIES)} math categories...")
    for name, parent, description in MATH_CATEGORIES:
        # Add to ontology if core has one
        if core.ontology:
            from dorian_ontology import Category

            core.ontology._add_category(
                Category(
                    name=name,
                    description=description,
                    parent=parent,
                    domain="mathematics",
                    level=core.ontology.categories.get(
                        parent, Category(name="", description="", level=3)
                    ).level
                    + 1,
                )
            )

        # Add is_a fact
        result = core.write(
            name,
            "subtype_of",
            parent,
            agent_id,
            source="mathematics_ontology",
            check_contradictions=False,
        )
        if result.success:
            count += 1

    # Add mathematical facts
    print(f"  Loading {len(MATH_FACTS)} math facts...")
    for s, p, o in MATH_FACTS:
        result = core.write(
            s,
            p,
            o,
            agent_id,
            source="mathematics_knowledge",
            check_contradictions=False,
        )
        if result.success:
            count += 1

    # Register inference rules
    print("  Registering math inference rules...")
    for domain, rule in get_math_inference_rules():
        core.inference_engine.add_domain_rule(domain, rule)

    print(f"  Total: {count} math facts loaded")
    return count


# =============================================================================
# MAIN - DEMO
# =============================================================================

if __name__ == "__main__":
    print("═" * 60)
    print("DORIAN MATHEMATICS DOMAIN")
    print("═" * 60)

    print(f"\nCategories: {len(MATH_CATEGORIES)}")
    print(f"Relations: {len(MATH_RELATIONS)}")
    print(f"Facts: {len(MATH_FACTS)}")

    print("\nSample categories:")
    for name, parent, desc in MATH_CATEGORIES[:10]:
        print(f"  {name} <- {parent}")

    print("\nSample facts:")
    for s, p, o in MATH_FACTS[:15]:
        print(f"  {s} {p} {o}")

    print("\nTo load into Dorian Core:")
    print("  from dorian_math import load_mathematics_into_core")
    print("  count = load_mathematics_into_core(core)")
